# Generated by Django 3.2.7 on 2021-09-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=512)),
                ('preview', models.CharField(max_length=512)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boulders',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('preview', models.CharField(max_length=512)),
                ('minimap', models.CharField(max_length=512)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='climbs.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=512)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Climbs',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('stars', models.IntegerField()),
                ('height', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('preview', models.CharField(max_length=512)),
                ('imgidx', models.IntegerField()),
                ('boulder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='climbs.boulders')),
            ],
        ),
        migrations.AddField(
            model_name='areas',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='climbs.places'),
        ),
    ]
