# Generated by Django 3.2.7 on 2021-09-21 21:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='boulders',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='climbs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='areas',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='boulders',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='boulders',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=512, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='climbs',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='climbs',
            name='points',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='areas',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='img',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='preview',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boulders',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boulders',
            name='minimap',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='boulders',
            name='preview',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='boulders',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climbs',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='climbs',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climbs',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climbs',
            name='imgidx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climbs',
            name='preview',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='climbs',
            name='stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='img',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
