# Generated by Django 3.2.7 on 2021-09-28 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0002_auto_20210921_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Locations',
        ),
        migrations.RenameField(
            model_name='areas',
            old_name='place',
            new_name='location',
        ),
    ]
