# Generated by Django 3.2.7 on 2021-09-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0003_auto_20210927_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areas',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boulders',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boulders',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locations',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
